# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e36f3268377216338fec9fa586e0e513f5a0019093163ec18080dac37ea17afbcbb16516ad0ae3c467e1a6f2122fbd6b7f90450ca666cf6c06a58c7f733220fc

test:
  secret_key_base: fd402a984665d190a6a49e75fc05b8e0492ddee305a2f6d724434b420afc1bc6d8926764c225f2084b44189a780c46b83e3b8517740dfbd6dbe9bd8b7482aa2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
